# Generated by Django 2.1.7 on 2019-03-09 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semestr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='parent_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='semestr.Semester'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='parent_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='semestr.Class'),
        ),
    ]
